### ISSUE TITLE
Error when interaction aborted

### ISSUE THREAD

**Issue by erbilsilik** [adrianbrs/nest-oidc-provider#11]
**Issue**: When the user aborts the interaction it breaks the application and it's not possible to use it until cookies are cleared.

```
{"error":"access_denied","error_description":"End-user aborted interaction"}
```

**Error**:
```
TypeError: Cannot read properties of undefined (reading 'getOIDCScopeEncountered')
```

**Comment by adrianbrs** [comment]
Hi @erbilsilik, can you provide the steps you did to reproduce this issue?
Thanks!

**Comment by erbilsilik** [comment]
Hi @adrianbrs,

You can use your **example** application to reproduce.

1. Start the application and go to the homepage
2. Press **Click here to authenticate** 
3. Enter user and password information and press **Sign in**
4. Try to go back or press **Cancel** in the next screen

Thanks!

**Comment by adrianbrs** [comment]
Oh, it's just a miskate in the example project, because the interaction is aborted the grant entity cannot be found.
https://github.com/adrianbrs/nest-oidc-provider/blob/c858b6f83d0d60e32c48512321f2e1341b812492/example/src/app.controller.ts#L30

Also, I will improve the example project to show these type of errors on homepage, instead of returning a JSON response.
Thanks for reporting this!
